version: '2'

services:
  crypto-investment:
    image: 'crypto-investment:latest'
    build:
      context: .
    container_name: crypto-investment
    depends_on:
      - crypto-db
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://crypto-db:5432/cryptodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  crypto-db:
    image: 'postgres:13.1-alpine'
    container_name: crypto-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cryptodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres