resilience4j.ratelimiter:
  instances:
    orderService:
      limitForPeriod: 10
      limitRefreshPeriod: 1m
      timeoutDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always