version: '2'

services:
  cryptodb:
    image: 'postgres:13.1-alpine'
    container_name: cryptodb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cryptodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres